docker network create $DOCKER_NETWORK

docker run -d --rm \
--network $DOCKER_NETWORK \
--env-file $DOCKER_ENV_FILE \
--name $DOCKER_IMAGE_NAME \
-p $DOCKER_EXTERNAL_PORT:$DOCKER_INTERNAL_PORT \
$DOCKER_USER/$DOCKER_IMAGE_NAME:$DOCKER_TAG
