PYTHON_VERSION=${PYTHON_VERSION:-3.8}

<<<<<<< HEAD
CARPETA_CODIGO=src
CARPETA_ENV=$CARPETA_CODIGO/env
RUTA_REQUIREMENTS=$CARPETA_CODIGO/requirements.txt
CARPETA_COMPILADO=dist
=======
export CARPETA_CODIGO=src
export CARPETA_ENV=$CARPETA_CODIGO/env
export RUTA_REQUIREMENTS=$CARPETA_CODIGO/requirements.txt
export CARPETA_COMPILADO=dist
>>>>>>> desarrollo
